package co.tpcreative.supersafe.model;

public enum EnumStatus {
    DOWNLOAD,
    UPLOAD,
    LOADING,
    DONE,
    SYNC_NONE,
    SYNC_ERROR,
    WRITE_FILE,
    CREATE_MAIN_CATEGORIES,
    CREATE_FOLDERS_IN_APP,
    GET_LIST_FILES_IN_APP,
    GET_LIST_FOLDERS_IN_APP,
    GET_DRIVE_ABOUT,
    DEVICE_ABOUT,
    CHECK_FOLDER_EXISTING,
    CHECK_FOLDER_IN_AkPP_EXISTING,
    REQUEST_ACCESS_TOKEN
}
