package co.tpcreative.supersafe.model;

public enum EnumStatus {
    DOWNLOAD,
    UPLOAD,
    LOADING,
    DONE,
    SYNC_NONE,
    SYNC_ERROR,
    WRITE_FILE,
    CREATE_MAIN_CATEGORIES,
    CREATE_FOLDERS_IN_APP,
    DELETE_SYNC_OWN_DATA,
    DELETE_SYNC_CLOUD_DATA,
    GET_LIST_FILES_IN_APP,
    GET_LIST_FOLDERS_IN_APP,
    GET_DRIVE_ABOUT,
    GET_FILES_INFO,
    DEVICE_ABOUT,
    CHECK_FOLDER_EXISTING,
    CHECK_FOLDER_IN_AkPP_EXISTING,
    REQUEST_ACCESS_TOKEN,
    GET_LIST_FILE,
    ADD_ITEMS,
    LOAD_MORE,
    SYNC_READY
}
