package co.tpcreative.supersafe.model

enum class EnumStatus {
    DOWNLOAD, UPLOAD, DONE, ERROR, SYNC_NONE, SYNC_ERROR, WRITE_FILE, DEVICE_ABOUT, REQUEST_ACCESS_TOKEN, GET_LIST_FILE, VERIFY, SCREEN_OFF, DISCONNECTED, CONNECTED, SET, RESET, RESTORE, RELOAD, REFRESH, UNLOCK_ALBUMS, FINISH, RECREATE, PLAY, CREATE, FAKE_PIN, CREATE_FAKE_PIN, DELETE, CHANGE, EXPORT, SHARE, MOVE, SIGN_IN, AUTHOR_SYNC, UNLOCK, PRIVATE_DONE, OTHER, CLOSED, REGISTER_OR_LOGIN, PREMIUM, SHOW_FLOATING_BUTTON, HIDE_FLOATING_BUTTON, UPDATED_VIEW_DETAIL_ALBUM, UPDATE_MOVE_NEW_ALBUM, IMPORTED_COMPLETELY, NO_SPACE_LEFT, NO_SPACE_LEFT_CLOUD, WAITING_LEFT, WAITING_DONE,MIGRATION_DONE,EXPIRED_SUBSCRIPTIONS,NONE
}